android.useAndroidX=true
org.gradle.java.home=C\:\\Program Files\\Android\\openjdk\\jdk-21.0.8

# Build performance
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=0

# Kotlin
kotlin.incremental=true

# Android
android.nonTransitiveRClass=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.uniquePackageNames=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
