[versions]
agp                  = "9.3.1"
kotlin               = "2.2.10"
coreKtx              = "1.13.1"
lifecycleRuntime     = "2.8.6"
activityCompose      = "1.10.1"
composeBom           = "2024.10.00"
navigationCompose    = "2.8.3"
billing              = "9.1.0"
splashscreen         = "1.0.1"
datastorePrefs       = "1.1.1"
reviewKtx            = "2.0.2"

[libraries]
androidx-core-ktx              = { group = "androidx.core",             name = "core-ktx",                    version.ref = "coreKtx" }
androidx-lifecycle-runtime     = { group = "androidx.lifecycle",        name = "lifecycle-runtime-ktx",       version.ref = "lifecycleRuntime" }
androidx-activity-compose      = { group = "androidx.activity",         name = "activity-compose",            version.ref = "activityCompose" }
compose-bom                    = { group = "androidx.compose",          name = "compose-bom",                 version.ref = "composeBom" }
compose-ui                     = { group = "androidx.compose.ui",       name = "ui" }
compose-ui-graphics            = { group = "androidx.compose.ui",       name = "ui-graphics" }
compose-ui-tooling-preview     = { group = "androidx.compose.ui",       name = "ui-tooling-preview" }
compose-ui-text-google-fonts   = { group = "androidx.compose.ui",       name = "ui-text-google-fonts" }
compose-material3               = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material",  name = "material-icons-extended" }
compose-ui-tooling             = { group = "androidx.compose.ui",       name = "ui-tooling" }
compose-ui-test-manifest       = { group = "androidx.compose.ui",       name = "ui-test-manifest" }
navigation-compose             = { group = "androidx.navigation",        name = "navigation-compose",         version.ref = "navigationCompose" }
billing                        = { group = "com.android.billingclient", name = "billing",                    version.ref = "billing" }
splashscreen                   = { group = "androidx.core",             name = "core-splashscreen",          version.ref = "splashscreen" }
datastore-preferences          = { group = "androidx.datastore",        name = "datastore-preferences",      version.ref = "datastorePrefs" }
material                       = { group = "com.google.android.material", name = "material",                version = "1.12.0" }
review-ktx                     = { group = "com.google.android.play",    name = "review-ktx",                 version.ref = "reviewKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose      = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
